# frozen_string_literal: true

require "rbconfig"
require "fileutils"

module Wreq
  module RustEnv
    WINDOWS_GNU_TARGET = "x86_64-pc-windows-gnu"
    WINDOWS_RUBY_PLATFORM = "x64-mingw-ucrt"

    # Uses the UCRT toolchain shipped with the active RubyInstaller installation.
    def self.activate
      unless RbConfig::CONFIG["host_os"].match?(/mingw|mswin/)
        FileUtils.rm_f(cargo_config_path)
        return
      end

      ruby_platform = RbConfig::CONFIG.fetch("arch")
      unless ruby_platform == WINDOWS_RUBY_PLATFORM
        raise "Unsupported Windows Ruby platform: #{ruby_platform}. " \
          "Use RubyInstaller UCRT (#{WINDOWS_RUBY_PLATFORM})."
      end

      ruby_root = RbConfig::CONFIG.fetch("prefix")
      msys_root = File.join(ruby_root, "msys64")
      ucrt_bin = File.join(msys_root, "ucrt64", "bin")
      msys_bin = File.join(msys_root, "usr", "bin")

      validate_tools(ucrt_bin, msys_bin)
      write_cargo_config(ucrt_bin, msys_bin)
      ENV["CARGO_BUILD_TARGET"] = WINDOWS_GNU_TARGET
      ENV["LIBCLANG_PATH"] = ucrt_bin
      ENV.delete("CMAKE_GENERATOR")
      ENV["PATH"] = [ucrt_bin, msys_bin, ENV.fetch("PATH", nil)].compact.join(File::PATH_SEPARATOR)
    end

    # Reports missing RubyInstaller packages before Cargo starts compiling.
    def self.validate_tools(ucrt_bin, msys_bin)
      required = %w[gcc.exe g++.exe gcc-ar.exe clang.exe libclang.dll cmake.exe]
        .map { |tool| File.join(ucrt_bin, tool) }
        .append(File.join(msys_bin, "make.exe"))
      missing = required.reject { |tool| File.file?(tool) }
      unless %w[pkgconf.exe pkg-config.exe].any? { |tool| File.file?(File.join(ucrt_bin, tool)) }
        missing << File.join(ucrt_bin, "pkgconf.exe")
      end
      return if missing.empty?

      raise "Missing RubyInstaller UCRT tools: #{missing.join(", ")}. " \
        "Install the Windows build dependencies documented in " \
        "docs/windows-gnu-tokio-crash.md."
    end

    # Generates machine-local Cargo defaults that work in command lines and IDEs.
    def self.write_cargo_config(ucrt_bin, msys_bin)
      config = <<~TOML
        # Generated by script/rust_env.rb for the active RubyInstaller.

        [build]
        target = "#{WINDOWS_GNU_TARGET}"

        [target.#{WINDOWS_GNU_TARGET}]
        linker = "#{File.join(ucrt_bin, "gcc.exe")}"

        [env]
        CC_x86_64_pc_windows_gnu = { value = "#{File.join(ucrt_bin, "gcc.exe")}", force = true }
        CXX_x86_64_pc_windows_gnu = { value = "#{File.join(ucrt_bin, "g++.exe")}", force = true }
        AR_x86_64_pc_windows_gnu = { value = "#{File.join(ucrt_bin, "gcc-ar.exe")}", force = true }
        CMAKE = { value = "#{File.join(ucrt_bin, "cmake.exe")}", force = true }
        CMAKE_GENERATOR = { value = "MSYS Makefiles", force = true }
        CMAKE_MAKE_PROGRAM = { value = "#{File.join(msys_bin, "make.exe")}", force = true }
        LIBCLANG_PATH = { value = "#{ucrt_bin}", force = true }
      TOML

      return if File.exist?(cargo_config_path) && File.binread(cargo_config_path) == config

      FileUtils.mkdir_p(File.dirname(cargo_config_path))
      File.binwrite(cargo_config_path, config)
    end

    # Returns the ignored Cargo configuration shared by Rake and language servers.
    def self.cargo_config_path
      File.expand_path("../.cargo/windows.toml", __dir__)
    end
  end
end
